# Generated by Django 5.2.7 on 2026-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='经度'),
        ),
    ]
