# Generated by Django 5.2.7 on 2026-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_latitude_address_longitude_dish_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, choices=[('flash_sale', '限时秒杀'), ('daily_deal', '每日优惠'), ('big_brand', '大牌一口价')], max_length=20, null=True, verbose_name='活动标签'),
        ),
    ]
