# Generated by Django 5.2.7 on 2026-01-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dish_original_price_dish_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wechat', '微信支付'), ('alipay', '支付宝')], max_length=20, null=True, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '待支付'), ('pending', '待接单'), ('accepted', '已接单'), ('cooking', '制作中'), ('delivering', '配送中'), ('delivered', '已送达'), ('cancelled', '已取消')], default='unpaid', max_length=20, verbose_name='状态'),
        ),
    ]
